language: node_js
node_js:
 - 11
cache: yarn

branches:
 only:
  - master
  - stable

before_install:
 - curl -o- -L https://yarnpkg.com/install.sh | bash
 - export PATH="$HOME/.yarn/bin:$PATH"

install:
 - yarn install

script:
 - yarn test

deploy:
 provider: netlify
 site: team-appendix
 auth: $NETLIFY_AUTH
 edge: true
 on:
  branch: master